
data_type: pazhou_34e8_scatters
data_path: ./datasets/indoor_e3_3cm_dataset_HV # indoor_e3_3cm_dataset # pazhou_34e8_scatters_result2_4TX # sionna_PKU_3e9 # pazhou_34e8_scatters_result2_4TX   # pazhou_34e8_scatters_result2_singleTX
train: TrainDataset.h5
test: DevDataset.h5
val: DevDataset.h5


